/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Профиль пользователя */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['database.User'];
          };
        };
        /** @description Пользователь не авторизован */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': string;
          };
        };
        /** @description Внутренняя ошибка сервера */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': string;
          };
        };
      };
    };
    put?: never;
    /** Обновить информацию профиля пользователя */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Интересы о пользователе */
      requestBody?: {
        content: {
          'application/json': unknown[];
        };
      };
      responses: {
        /** @description Пользователь успешно обновлен */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
        /** @description Пользователь не авторизован */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
        /** @description Внутренняя ошибка сервера */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/me/photo': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Обновить информацию профиля пользователя */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Фото пользователя */
      requestBody?: {
        content: {
          'application/json': number[];
        };
      };
      responses: {
        /** @description Пользователь успешно обновлен */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
        /** @description Внутренняя ошибка сервера */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/me/widgets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Обновить виджет */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'multipart/form-data': {
            /** @description Данные виджета */
            data?: number[];
            /** @description Файлы виджета */
            files?: unknown[];
          };
        };
      };
      responses: {
        /** @description Виджет успешно обновлен */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
        /** @description Внутренняя ошибка сервера */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
      };
    };
    /** Создать виджет */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'multipart/form-data': {
            /** @description Данные виджета */
            data?: number[];
            /** @description Файлы виджета */
            files?: unknown[];
          };
        };
      };
      responses: {
        /** @description Виджет успешно создан */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
        /** @description Внутренняя ошибка сервера */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
      };
    };
    /** Удалить виджет */
    delete: {
      parameters: {
        query: {
          /** @description id виджета */
          widget_id: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Виджет удален */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
        /** @description Внутренняя ошибка сервера */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/me/widgets/order': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Обновить очередь виджета */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'multipart/form-data': {
            /** @description id виджета */
            widget_id: string;
            /**
             * Format: int32
             * @description Изменение позиции виджета виджета
             */
            order: number;
          };
        };
      };
      responses: {
        /** @description Очередь успешно обновлена */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
        /** @description Внутренняя ошибка сервера */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/me/widgets/photo': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Удалить фото виджета */
    delete: {
      parameters: {
        query: {
          /** @description id виджета */
          widget_id: string;
          /** @description Позиция фото в списке */
          index: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Фото виджета удалено */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
        /** @description Внутренняя ошибка сервера */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/namespace': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Обновить информацию о неймспейсе */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'multipart/form-data': {
            /** @description Название неймспейса */
            title?: string;
            /**
             * Format: binary
             * @description Картинка неймспейса
             */
            photo?: string;
            /** @description Описание неймспейса */
            description?: string;
          };
        };
      };
      responses: {
        /** @description Неймспейс успешно обновлен */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
        /** @description Внутренняя ошибка сервера */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
      };
    };
    /** Создать неймспейс */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'multipart/form-data': {
            /** @description Название неймспейса */
            title: string;
            /**
             * Format: binary
             * @description Картинка неймспейса
             */
            photo: string;
            /** @description Описание неймспейса */
            description: string;
          };
        };
      };
      responses: {
        /** @description Неймспейс успешно создан */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
        /** @description Внутренняя ошибка сервера */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
      };
    };
    /** Удалить неймспейс */
    delete: {
      parameters: {
        query: {
          /** @description Название неймспейса */
          id: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Неймспейс успешно удален */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
        /** @description Этот пользователь не админ неймспейса */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
        /** @description Внутренняя ошибка сервера */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/namespace/{namespace_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить ленту из анкет пользователей неймспейса */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description id неймспейса */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['database.User'][];
          };
        };
        /** @description Внутренняя ошибка сервера */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': string;
          };
        };
      };
    };
    put?: never;
    /** Зайти в неймспейс */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'multipart/form-data': {
            /** @description id неймспейса */
            namespace: string;
            /** @description инвайт код для входа в неймспейс */
            invite_code: string;
          };
        };
      };
      responses: {
        /** @description Успешный вход */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
        /** @description Неверный код входа */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
        /** @description Внутренняя ошибка сервера */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
      };
    };
    /** Выйти из неймспейса */
    delete: {
      parameters: {
        query: {
          /** @description id неймспейса */
          namespace: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Успешный вход */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
        /** @description Внутренняя ошибка сервера */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/vote': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Проголосовать в опросе */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'multipart/form-data': {
            /** @description id виджета опроса */
            survey?: string;
            /** @description вариант опроса */
            option?: string;
          };
        };
      };
      responses: {
        /** @description Голос засчитан */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
        /** @description Внутренняя ошибка сервера */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': string;
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Основные данные профиля и связанные виджеты. */
    'database.User': {
      birth_date?: string;
      gender?: string;
      interests?: string[];
      location?: string;
      miniapp_name?: string;
      tg_user?: string;
      user_info?: string;
      user_photo?: number[];
      widgets?: components['schemas']['database.Widget'][];
    };
    /** @description Виджет */
    'database.Widget': {
      additionalData?: string;
      data?: string;
      files?: number[][];
      id?: string;
      namespace?: string;
      order?: number;
      user?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
