// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Получить токен авторизации",
                "parameters": [
                    {
                        "description": "tma initData",
                        "name": "initData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Токен выдан",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Не валидный токен авторизации",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Пользователь не записан в базу данных",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/games": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Игры пользователя из его steam профиля для виджета",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ссылка на профиль",
                        "name": "link",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "JSON, содержащий список игр",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/database.Error"
                        }
                    }
                }
            }
        },
        "/api/me": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Профиль пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.User"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/database.Error"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/database.Error"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "summary": "Обновить информацию профиля пользователя",
                "parameters": [
                    {
                        "description": "Имя пользователя",
                        "name": "name",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Локация пользователя",
                        "name": "location",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Пол пользователя",
                        "name": "gender",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Дата рождения пользователя",
                        "name": "birth_date",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Информация о пользователе",
                        "name": "info",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Интересы о пользователе",
                        "name": "interests",
                        "in": "body",
                        "schema": {
                            "type": "array"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Пользователь успешно обновлен"
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/database.Error"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/database.Error"
                        }
                    }
                }
            }
        },
        "/api/me/photo": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "summary": "Обновить информацию профиля пользователя",
                "parameters": [
                    {
                        "description": "Фото пользователя",
                        "name": "user_photo",
                        "in": "body",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Пользователь успешно обновлен"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/database.Error"
                        }
                    }
                }
            }
        },
        "/api/me/widgets": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "summary": "Создать виджет",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "integer",
                            "format": "int32"
                        },
                        "collectionFormat": "csv",
                        "description": "Данные виджета",
                        "name": "data",
                        "in": "formData"
                    },
                    {
                        "type": "array",
                        "description": "Файлы виджета",
                        "name": "files",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Виджет успешно создан"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/database.Error"
                        }
                    }
                }
            },
            "delete": {
                "summary": "Удалить виджет",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id виджета",
                        "name": "widget_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Виджет удален"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/database.Error"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "multipart/form-data"
                ],
                "summary": "Обновить виджет",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "integer",
                            "format": "int32"
                        },
                        "collectionFormat": "csv",
                        "description": "Данные виджета",
                        "name": "data",
                        "in": "formData"
                    },
                    {
                        "type": "array",
                        "description": "Файлы виджета",
                        "name": "files",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Виджет успешно обновлен"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/database.Error"
                        }
                    }
                }
            }
        },
        "/api/me/widgets/order": {
            "patch": {
                "consumes": [
                    "multipart/form-data"
                ],
                "summary": "Обновить очередь виджета",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id виджета",
                        "name": "widget_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Изменение позиции виджета виджета",
                        "name": "order",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Очередь успешно обновлена"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/database.Error"
                        }
                    }
                }
            }
        },
        "/api/me/widgets/photo": {
            "delete": {
                "summary": "Удалить фото виджета",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id виджета",
                        "name": "widget_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Позиция фото в списке",
                        "name": "index",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Фото виджета удалено"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/database.Error"
                        }
                    }
                }
            }
        },
        "/api/namespace": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "summary": "Создать неймспейс",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название неймспейса",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Картинка неймспейса",
                        "name": "photo",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Описание неймспейса",
                        "name": "description",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Неймспейс успешно создан"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/database.Error"
                        }
                    }
                }
            },
            "delete": {
                "summary": "Удалить неймспейс",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название неймспейса",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Неймспейс успешно удален"
                    },
                    "403": {
                        "description": "Этот пользователь не админ неймспейса",
                        "schema": {
                            "$ref": "#/definitions/database.Error"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/database.Error"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "multipart/form-data"
                ],
                "summary": "Обновить информацию о неймспейсе",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название неймспейса",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Картинка неймспейса",
                        "name": "photo",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Описание неймспейса",
                        "name": "description",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Неймспейс успешно обновлен"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/database.Error"
                        }
                    }
                }
            }
        },
        "/api/namespace/{namespace_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Получить ленту из анкет пользователей неймспейса",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id неймспейса",
                        "name": "namespace_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.PageData"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/database.Error"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "summary": "Зайти в неймспейс",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id неймспейса",
                        "name": "namespace",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "инвайт код для входа в неймспейс",
                        "name": "invite_code",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный вход"
                    },
                    "403": {
                        "description": "Неверный код входа",
                        "schema": {
                            "$ref": "#/definitions/database.Error"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/database.Error"
                        }
                    }
                }
            },
            "delete": {
                "summary": "Выйти из неймспейса",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id неймспейса",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный вход"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/database.Error"
                        }
                    }
                }
            }
        },
        "/api/tg": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Проверить существование пользователя в бд",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id пользователя",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/database.User"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/database.Error"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Проверить существование пользователя в бд",
                "parameters": [
                    {
                        "description": "tg id пользователя",
                        "name": "id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "tg username пользователя",
                        "name": "username",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "tg firstname пользователя",
                        "name": "firstname",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/database.Error"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "summary": "Скрыть/показывать анкету другим пользователям",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id пользователя",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/database.Error"
                        }
                    }
                }
            },
            "patch": {
                "produces": [
                    "application/json"
                ],
                "summary": "Скрыть/показывать анкету другим пользователям",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id пользователя",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/database.Error"
                        }
                    }
                }
            }
        },
        "/api/vote": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "summary": "Проголосовать в опросе",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id виджета опроса",
                        "name": "survey",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "вариант опроса",
                        "name": "option",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Голос засчитан"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/database.Error"
                        }
                    }
                }
            }
        },
        "/api/worker/autocomplete": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Предложенные пользователю интересы",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ввод пользователя",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.AutocompleteResponse"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации",
                        "schema": {
                            "$ref": "#/definitions/database.Error"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/database.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "database.Error": {
            "description": "Ошибка",
            "type": "object",
            "properties": {
                "cause": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                }
            }
        },
        "database.User": {
            "description": "Основные данные профиля и связанные виджеты.",
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "hide": {
                    "type": "boolean"
                },
                "interests": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "location": {
                    "type": "string"
                },
                "miniapp_name": {
                    "type": "string"
                },
                "personality_test": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "tg_user": {
                    "type": "string"
                },
                "user_info": {
                    "type": "string"
                },
                "user_photo": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "widgets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.Widget"
                    }
                }
            }
        },
        "database.Vote": {
            "description": "Голос в опросе",
            "type": "object",
            "properties": {
                "option": {
                    "type": "integer"
                },
                "survey": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "database.Widget": {
            "description": "Виджет",
            "type": "object",
            "properties": {
                "additionalData": {
                    "type": "string"
                },
                "data": {
                    "type": "string"
                },
                "files": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "integer",
                            "format": "int32"
                        }
                    }
                },
                "id": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "order": {
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/database.User"
                },
                "vote": {
                    "$ref": "#/definitions/database.Vote"
                }
            }
        },
        "handlers.AutocompleteResponse": {
            "description": "Ответ autocomplete эндпоинта воркера.",
            "type": "object",
            "properties": {
                "q": {
                    "type": "string"
                },
                "response": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handlers.PageData": {
            "description": "Данные анкеты (все поля database.User + tg username)",
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "hide": {
                    "type": "boolean"
                },
                "interests": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "location": {
                    "type": "string"
                },
                "miniapp_name": {
                    "type": "string"
                },
                "personality_test": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "tg_user": {
                    "type": "string"
                },
                "user_info": {
                    "type": "string"
                },
                "user_photo": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "username": {
                    "type": "string"
                },
                "widgets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.Widget"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Shumi API",
	Description:      "Shumi API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
