definitions:
  database.Error:
    description: Ошибка
    properties:
      cause:
        type: string
      status_code:
        type: integer
    type: object
  database.User:
    description: Основные данные профиля и связанные виджеты.
    properties:
      birth_date:
        type: string
      gender:
        type: string
      hide:
        type: boolean
      interests:
        items:
          type: string
        type: array
      location:
        type: string
      miniapp_name:
        type: string
      personality_test:
        items:
          type: integer
        type: array
      tg_user:
        type: string
      user_info:
        type: string
      user_photo:
        items:
          type: integer
        type: array
      widgets:
        items:
          $ref: '#/definitions/database.Widget'
        type: array
    type: object
  database.Vote:
    description: Голос в опросе
    properties:
      option:
        type: integer
      survey:
        type: string
      user:
        type: string
    type: object
  database.Widget:
    description: Виджет
    properties:
      additionalData:
        type: string
      data:
        type: string
      files:
        items:
          items:
            format: int32
            type: integer
          type: array
        type: array
      id:
        type: string
      namespace:
        type: string
      order:
        type: integer
      user:
        $ref: '#/definitions/database.User'
      vote:
        $ref: '#/definitions/database.Vote'
    type: object
  handlers.AutocompleteResponse:
    description: Ответ autocomplete эндпоинта воркера.
    properties:
      q:
        type: string
      response:
        items:
          type: string
        type: array
    type: object
  handlers.PageData:
    description: Данные анкеты (все поля database.User + tg username)
    properties:
      birth_date:
        type: string
      gender:
        type: string
      hide:
        type: boolean
      interests:
        items:
          type: string
        type: array
      location:
        type: string
      miniapp_name:
        type: string
      personality_test:
        items:
          type: integer
        type: array
      tg_user:
        type: string
      user_info:
        type: string
      user_photo:
        items:
          type: integer
        type: array
      username:
        type: string
      widgets:
        items:
          $ref: '#/definitions/database.Widget'
        type: array
    type: object
info:
  contact: {}
  description: Shumi API
  title: Shumi API
  version: "1.0"
paths:
  /api/auth:
    post:
      parameters:
      - description: tma initData
        in: body
        name: initData
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Токен выдан
          schema:
            type: string
        "401":
          description: Не валидный токен авторизации
          schema:
            type: string
        "403":
          description: Пользователь не записан в базу данных
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Получить токен авторизации
  /api/games:
    get:
      parameters:
      - description: Ссылка на профиль
        in: query
        name: link
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: JSON, содержащий список игр
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/database.Error'
      summary: Игры пользователя из его steam профиля для виджета
  /api/me:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database.User'
        "401":
          description: Пользователь не авторизован
          schema:
            $ref: '#/definitions/database.Error'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/database.Error'
      summary: Профиль пользователя
    patch:
      consumes:
      - application/json
      parameters:
      - description: Имя пользователя
        in: body
        name: name
        schema:
          type: string
      - description: Локация пользователя
        in: body
        name: location
        schema:
          type: string
      - description: Пол пользователя
        in: body
        name: gender
        schema:
          type: string
      - description: Дата рождения пользователя
        in: body
        name: birth_date
        schema:
          type: string
      - description: Информация о пользователе
        in: body
        name: info
        schema:
          type: string
      - description: Интересы о пользователе
        in: body
        name: interests
        schema:
          type: array
      responses:
        "200":
          description: Пользователь успешно обновлен
        "401":
          description: Пользователь не авторизован
          schema:
            $ref: '#/definitions/database.Error'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/database.Error'
      summary: Обновить информацию профиля пользователя
  /api/me/photo:
    post:
      consumes:
      - application/json
      parameters:
      - description: Фото пользователя
        in: body
        name: user_photo
        schema:
          items:
            type: integer
          type: array
      responses:
        "200":
          description: Пользователь успешно обновлен
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/database.Error'
      summary: Обновить информацию профиля пользователя
  /api/me/widgets:
    delete:
      parameters:
      - description: id виджета
        in: query
        name: widget_id
        required: true
        type: string
      responses:
        "200":
          description: Виджет удален
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/database.Error'
      summary: Удалить виджет
    patch:
      consumes:
      - multipart/form-data
      parameters:
      - collectionFormat: csv
        description: Данные виджета
        in: formData
        items:
          format: int32
          type: integer
        name: data
        type: array
      - description: Файлы виджета
        in: formData
        name: files
        type: array
      responses:
        "200":
          description: Виджет успешно обновлен
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/database.Error'
      summary: Обновить виджет
    post:
      consumes:
      - multipart/form-data
      parameters:
      - collectionFormat: csv
        description: Данные виджета
        in: formData
        items:
          format: int32
          type: integer
        name: data
        type: array
      - description: Файлы виджета
        in: formData
        name: files
        type: array
      responses:
        "200":
          description: Виджет успешно создан
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/database.Error'
      summary: Создать виджет
  /api/me/widgets/order:
    patch:
      consumes:
      - multipart/form-data
      parameters:
      - description: id виджета
        in: formData
        name: widget_id
        required: true
        type: string
      - description: Изменение позиции виджета виджета
        in: formData
        name: order
        required: true
        type: integer
      responses:
        "200":
          description: Очередь успешно обновлена
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/database.Error'
      summary: Обновить очередь виджета
  /api/me/widgets/photo:
    delete:
      parameters:
      - description: id виджета
        in: query
        name: widget_id
        required: true
        type: string
      - description: Позиция фото в списке
        in: query
        name: index
        required: true
        type: integer
      responses:
        "200":
          description: Фото виджета удалено
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/database.Error'
      summary: Удалить фото виджета
  /api/namespace:
    delete:
      parameters:
      - description: Название неймспейса
        in: query
        name: id
        required: true
        type: string
      responses:
        "200":
          description: Неймспейс успешно удален
        "403":
          description: Этот пользователь не админ неймспейса
          schema:
            $ref: '#/definitions/database.Error'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/database.Error'
      summary: Удалить неймспейс
    patch:
      consumes:
      - multipart/form-data
      parameters:
      - description: Название неймспейса
        in: formData
        name: title
        type: string
      - description: Картинка неймспейса
        in: formData
        name: photo
        type: file
      - description: Описание неймспейса
        in: formData
        name: description
        type: string
      responses:
        "200":
          description: Неймспейс успешно обновлен
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/database.Error'
      summary: Обновить информацию о неймспейсе
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Название неймспейса
        in: formData
        name: title
        required: true
        type: string
      - description: Картинка неймспейса
        in: formData
        name: photo
        required: true
        type: file
      - description: Описание неймспейса
        in: formData
        name: description
        required: true
        type: string
      responses:
        "200":
          description: Неймспейс успешно создан
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/database.Error'
      summary: Создать неймспейс
  /api/namespace/{namespace_id}:
    delete:
      parameters:
      - description: id неймспейса
        in: query
        name: namespace
        required: true
        type: string
      responses:
        "200":
          description: Успешный вход
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/database.Error'
      summary: Выйти из неймспейса
    get:
      parameters:
      - description: id неймспейса
        in: path
        name: namespace_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.PageData'
            type: array
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/database.Error'
      summary: Получить ленту из анкет пользователей неймспейса
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: id неймспейса
        in: formData
        name: namespace
        required: true
        type: string
      - description: инвайт код для входа в неймспейс
        in: formData
        name: invite_code
        required: true
        type: string
      responses:
        "200":
          description: Успешный вход
        "403":
          description: Неверный код входа
          schema:
            $ref: '#/definitions/database.Error'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/database.Error'
      summary: Зайти в неймспейс
  /api/tg:
    delete:
      parameters:
      - description: id пользователя
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/database.Error'
      summary: Скрыть/показывать анкету другим пользователям
    get:
      parameters:
      - description: id пользователя
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/database.User'
            type: array
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/database.Error'
      summary: Проверить существование пользователя в бд
    patch:
      parameters:
      - description: id пользователя
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/database.Error'
      summary: Скрыть/показывать анкету другим пользователям
    post:
      parameters:
      - description: tg id пользователя
        in: body
        name: id
        required: true
        schema:
          type: string
      - description: tg username пользователя
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: tg firstname пользователя
        in: body
        name: firstname
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/database.Error'
      summary: Проверить существование пользователя в бд
  /api/vote:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: id виджета опроса
        in: formData
        name: survey
        type: string
      - description: вариант опроса
        in: formData
        name: option
        type: string
      responses:
        "200":
          description: Голос засчитан
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/database.Error'
      summary: Проголосовать в опросе
  /api/worker/autocomplete:
    get:
      parameters:
      - description: Ввод пользователя
        in: query
        name: q
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.AutocompleteResponse'
        "401":
          description: Ошибка авторизации
          schema:
            $ref: '#/definitions/database.Error'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/database.Error'
      summary: Предложенные пользователю интересы
swagger: "2.0"
